"""Build and resolve local MCP packages generated by Lumena.

This module is intentionally small and deterministic. It creates a minimal
stdio MCP server package that can be installed through the existing uv-backed
MCPSandboxRunner without adding a new runner transport.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

from src.utils.paths import DATA_DIR


_DEFAULT_ROOT = DATA_DIR / "mcp_local_creation"
_PACKAGES_SUBDIR = "packages"
_SERVER_ID_RE = re.compile(r"^[a-z0-9][a-z0-9_.\-]{0,63}$")
_CONTROL_RE = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]")
_WINDOWS_RESERVED_NAMES = frozenset({
    "con", "prn", "aux", "nul",
    "com1", "com2", "com3", "com4", "com5",
    "com6", "com7", "com8", "com9",
    "lpt1", "lpt2", "lpt3", "lpt4", "lpt5",
    "lpt6", "lpt7", "lpt8", "lpt9",
})
_SAFE_TEXT_MAX = 512


class LocalMCPPackageError(Exception):
    """Short-code error for local package generation/resolution."""


@dataclass(frozen=True)
class LocalMCPPackageInfo:
    server_id: str
    package_dir: Path
    module_name: str
    manifest_path: Path
    relative_package_path: str


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _validate_server_id(server_id: Any) -> str:
    if not isinstance(server_id, str) or not _SERVER_ID_RE.match(server_id):
        raise LocalMCPPackageError("server_id_invalid")
    if ".." in server_id or "/" in server_id or "\\" in server_id:
        raise LocalMCPPackageError("server_id_invalid")
    if server_id.split(".", 1)[0] in _WINDOWS_RESERVED_NAMES:
        raise LocalMCPPackageError("server_id_invalid")
    return server_id


def _module_name(server_id: str) -> str:
    return "lumena_mcp_" + re.sub(r"[^a-z0-9_]", "_", server_id)


def _clean_text(value: Any, *, fallback: str) -> str:
    if not isinstance(value, str):
        return fallback
    text = _CONTROL_RE.sub("", value).strip()
    text = " ".join(text.split())
    if not text:
        return fallback
    return text[:_SAFE_TEXT_MAX]


def _package_root(root_dir: Optional[Path]) -> Path:
    return (root_dir or _DEFAULT_ROOT) / _PACKAGES_SUBDIR


def local_mcp_package_info(server_id: str, *, root_dir: Optional[Path] = None) -> LocalMCPPackageInfo:
    sid = _validate_server_id(server_id)
    package_dir = _package_root(root_dir) / sid
    module_name = _module_name(sid)
    return LocalMCPPackageInfo(
        server_id=sid,
        package_dir=package_dir,
        module_name=module_name,
        manifest_path=package_dir / "lumena_mcp_manifest.json",
        relative_package_path=f"{_PACKAGES_SUBDIR}/{sid}",
    )


def resolve_local_mcp_package(server_id: str, *, root_dir: Optional[Path] = None) -> LocalMCPPackageInfo:
    info = local_mcp_package_info(server_id, root_dir=root_dir)
    if not info.package_dir.exists() or not info.manifest_path.exists():
        raise LocalMCPPackageError("local_package_missing")
    module_dir = info.package_dir / info.module_name
    if not (info.package_dir / "pyproject.toml").exists() or not (module_dir / "__main__.py").exists():
        raise LocalMCPPackageError("local_package_invalid")
    return info


def build_local_mcp_package(
    *,
    server_id: str,
    intent: str,
    intent_hash: str,
    root_dir: Optional[Path] = None,
) -> LocalMCPPackageInfo:
    info = local_mcp_package_info(server_id, root_dir=root_dir)
    clean_intent = _clean_text(intent, fallback="Local MCP request")
    clean_hash = intent_hash if isinstance(intent_hash, str) and len(intent_hash) == 64 else ""
    module_dir = info.package_dir / info.module_name
    module_dir.mkdir(parents=True, exist_ok=True)

    pyproject = f"""[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "{info.module_name.replace('_', '-')}"
version = "0.1.0"
description = "Lumena generated local MCP server"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["."]
include = ["{info.module_name}*"]
"""
    (info.package_dir / "pyproject.toml").write_text(pyproject, encoding="utf-8")
    (module_dir / "__init__.py").write_text("__all__ = []\n", encoding="utf-8")
    (module_dir / "__main__.py").write_text(
        "from .server import main\n\nif __name__ == \"__main__\":\n    main()\n",
        encoding="utf-8",
    )
    server_py = _server_source(
        server_id=info.server_id,
        intent=clean_intent,
        intent_hash=clean_hash,
    )
    (module_dir / "server.py").write_text(server_py, encoding="utf-8")

    manifest = {
        "server_id": info.server_id,
        "module_name": info.module_name,
        "intent_hash": clean_hash,
        "created_at": _now_iso(),
        "tools": ["describe_local_mcp_request"],
    }
    info.manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    (info.package_dir / "README.md").write_text(
        "# Lumena local MCP\n\n"
        "Generated by Lumena from an approved local MCP creation request.\n",
        encoding="utf-8",
    )
    return info


def _server_source(*, server_id: str, intent: str, intent_hash: str) -> str:
    sid = json.dumps(server_id, ensure_ascii=False)
    req = json.dumps(intent, ensure_ascii=False)
    ih = json.dumps(intent_hash, ensure_ascii=False)
    return f'''from __future__ import annotations

import json
import sys
from datetime import datetime, timezone

SERVER_ID = {sid}
INTENT = {req}
INTENT_HASH = {ih}


def _reply(message_id, result=None, error=None):
    payload = {{"jsonrpc": "2.0", "id": message_id}}
    if error is not None:
        payload["error"] = error
    else:
        payload["result"] = result
    sys.stdout.write(json.dumps(payload, ensure_ascii=False) + "\\n")
    sys.stdout.flush()


def _tool_schema():
    return {{
        "type": "object",
        "properties": {{
            "note": {{"type": "string", "description": "Optional context note."}}
        }},
        "additionalProperties": False,
    }}


def _tools():
    return [{{
        "name": "describe_local_mcp_request",
        "description": "Describe the approved Lumena local MCP creation request.",
        "inputSchema": _tool_schema(),
    }}]


def _handle(method, params):
    if method == "initialize":
        return {{
            "protocolVersion": "2024-11-05",
            "capabilities": {{"tools": {{}}}},
            "serverInfo": {{"name": SERVER_ID, "version": "0.1.0"}},
        }}
    if method == "tools/list":
        return {{"tools": _tools()}}
    if method == "tools/call":
        name = (params or {{}}).get("name")
        if name != "describe_local_mcp_request":
            return {{
                "content": [{{"type": "text", "text": "Unknown local MCP tool."}}],
                "isError": True,
            }}
        text = (
            f"Local MCP {{SERVER_ID}} generated by Lumena. "
            f"Approved request: {{INTENT}}. "
            f"Intent hash: {{INTENT_HASH}}. "
            f"Called at {{datetime.now(timezone.utc).isoformat()}}."
        )
        return {{"content": [{{"type": "text", "text": text}}], "isError": False}}
    return None


def main():
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            msg = json.loads(line)
        except Exception:
            continue
        message_id = msg.get("id")
        method = msg.get("method")
        if message_id is None:
            continue
        result = _handle(method, msg.get("params"))
        if result is None:
            _reply(message_id, error={{"code": -32601, "message": "Method not found"}})
        else:
            _reply(message_id, result=result)
'''


__all__ = [
    "LocalMCPPackageError",
    "LocalMCPPackageInfo",
    "build_local_mcp_package",
    "local_mcp_package_info",
    "resolve_local_mcp_package",
]
